# The list of Builtin Module Implementation Classes included with this distribution.
# Used by PeerGroup Implementation.

# Since the peer groups refer to other modules in their ModuleImplAdvertisements it's necessary to load them last.

urn:jxta:uuid-deadbeefdeafbabafeedbabe000000010106 net.jxta.compatibility.impl.peergroup.Platform Standard World PeerGroup Reference Implementation
urn:jxta:uuid-deadbeefdeafbabafeedbabe000000010206 net.jxta.compatibility.impl.peergroup.ShadowPeerGroup Default Network PeerGroup Reference Implementation
urn:jxta:uuid-deadbeefdeafbabafeedbabe000000010306 net.jxta.compatibility.impl.peergroup.StdPeerGroup General Purpose Peer Group Implementation
